//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnionArchitecture.Repository.ADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ToDo
    {
        public int Id { get; set; }
        public string TaskName { get; set; }
        public string TaskDetails { get; set; }
        public Nullable<System.DateTime> TaskDate { get; set; }
        public Nullable<int> TaskStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
