//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnionArchitecture.Repository.ADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_M_Status
    {
        public int Id { get; set; }
        public string Status { get; set; }
    }
}
